<?php
return [


    [
        'city'    => 'ADANA',
        'company' => 'DOĞA BİSİKLET',
        'address' => 'KENAN EVREN BULVARI HALK BANK KARŞISI KAROL SİTESİ B BLOK 1/A',
        'phone'   => '0322 458 09 80',
        'email'   => 'tekinguleken@hotmail.com',
    ],
    [
        'city'    => 'ANKARA',
        'company' => 'PERFORMANS BİSİKLET',
        'address' => 'ÇARŞI CAD LEVENT SOK NO:100/A YENİMAHALLE',
        'phone'   => '0312 343 21 17',
        'email'   => 'info@performansbisiklet.com',
    ],
    [
        'city'    => 'ANTALYA',
        'company' => 'BIKE HOUSE',
        'address' => 'BAHÇELİEVLER MAH. HIZIR REİS CD. BÜYÜKGELENDOST APT. NO:19, 07102',
        'phone'   => '0242 244 80 01',
        'email'   => 'bikehouseantalya@gmail.com',
    ],
    [
        'city'    => 'ANTALYA',
        'company' => 'UYSAL BİSİKLET & MOTOR',
        'address' => 'YALI MAH SİDE BULVARI NO:67/B SİDE',
        'phone'   => '0242 753 31 00',
        'email'   => 'uysal_motor@hotmail.com',
    ],
    [
        'city'    => 'ANTALYA',
        'company' => 'UYSAL MOTOR MANAVGAT',
        'address' => 'AŞAĞI PAZARCI MAH 1018 SOK NO:38 MANAVGAT',
        'phone'   => '0242 742 42 41',
        'email'   => 'uysal_motor@hotmail.com',
    ],
    [
        'city'    => 'ESKİŞEHİR',
        'company' => 'VOLKAN BİSİKLET',
        'address' => 'MAMURE CADDESİ HASAN POLATKAN CADDESİ NO:56/C TEPEBAŞI',
        'phone'   => '0222 230 10 08',
        'email'   => 'volkanbisiklet@volkanbisiklet.com',
    ],
    [
        'city'    => 'ESKİŞEHİR',
        'company' => 'ÇINAR BİSİKLET',
        'address' => 'HAYRİYE MAH. ULUTAŞ SOK. NO: 24 TEPEBAŞI',
        'phone'   => '0222 234 49 42',
        'email'   => 'cinarbisiklet@hotmail.com',
    ],
    [
        'city'    => 'İSTANBUL',
        'company' => 'BİSİKLET SEPETİ',
        'address' => 'MEHMET ŞEVKİ PAŞA CAD. NO:14-2 34744 BOSTANCI KADIKÖY',
        'phone'   => '0216 372 05 95',
        'email'   => 'info@bisikletsepeti.com',
    ],
    [
        'city'    => 'İSTANBUL',
        'company' => 'YEŞİL BİSİKLET FENERBAHÇE',
        'address' => 'LALEZAR SK. NO:6/A SELAMİÇEŞME KADIKÖY',
        'phone'   => '0216 301 15 50-51',
        'email'   => 'yesil@yesilbisiklet.com',
    ],
    [
        'city'    => 'İSTANBUL',
        'company' => 'YEŞİL BİSİKLET GÖKTÜRK',
        'address' => 'İSTANBUL CAD. NO: 48/G GÖKTÜRK EYÜP',
        'phone'   => '0212 322 82 50',
        'email'   => 'yesil@yesilbisiklet.com',
    ],
    [
        'city'    => 'İSTANBUL',
        'company' => 'YEŞİL BİSİKLET ATAŞEHİR',
        'address' => 'ORTABAHAR SK. NO:31/5 BARBAROS (Palladium Çapraz Karşısı)',
        'phone'   => '0216 291 20 50-51',
        'email'   => 'yesil@yesilbisiklet.com',
    ],
    [
        'city'    => 'İSTANBUL',
        'company' => 'BİSİKLET EVİM',
        'address' => 'BOSTANCI MH. PROF.DR. ALİ NİHAT TARLAN CD. NO:27/1 KADIKÖY',
        'phone'   => '0216 445 12 61',
        'email'   => 'info@bisikletevim.com',
    ],
    [
        'city'    => 'İSTANBUL',
        'company' => 'BİSİKLET HASTANESİ',
        'address' => 'BAHÇEŞEHİR MAH 1.KISIM İSTASYON ÇIKMAZI NO:7/A BAHÇEŞEHİR',
        'phone'   => '0538 056 27 55',
        'email'   => 'bahcesehir@bisiklethastanesi.com',
    ],
    [
        'city'    => 'İSTANBUL',
        'company' => 'TEMİZ İŞ BİSİKLET',
        'address' => 'ATATÜRK CAD.ULAŞTIRICI SOK. NO:8 KOZYATAĞI/KADIKÖY',
        'phone'   => '0506 656 15 53',
        'email'   => 'temizisbike@gmail.com',
    ],
    [
        'city'    => 'İZMİR',
        'company' => 'DORUK BİSİKLET',
        'address' => 'MUSTAFA KEMAL SAHİL BLV. NO:415-415/A KÜÇÜKYALI',
        'phone'   => '0232 232 06 00',
        'email'   => 'info@dorukbisiklet.com',
    ],
    [
        'city'    => 'İZMİR',
        'company' => 'SEDA BİSİKLET',
        'address' => '1698 SOKAK NO:16 KARŞIYAKA',
        'phone'   => '0232 369 49 79',
        'email'   => 'info@sedabisiklet.com',
    ],
    [
        'city'    => 'KONYA',
        'company' => 'PINARELLİ BİSİKLET',
        'address' => 'SAHİBİ ATA MAH. FURGANDEDE CAD. YENİ LARENDE YOLU NO:25/A',
        'phone'   => '0332 353 21 30',
        'email'   => 'ahmet@pinarelli.com',
    ],
    [
        'city'    => 'MUĞLA',
        'company' => 'PEDALLA BİSİKLET',
        'address' => 'E. BEYAZIT MAH. UĞUR MUMCU BULV AYLİN KARACA KVŞ. ARDIŞ SOK NO:2/B',
        'phone'   => '0252 214 76 96',
        'email'   => 'info@pedalla.com.tr',
    ],
    [
        'city'    => 'SAMSUN',
        'company' => 'MODA BİSİKLET',
        'address' => 'YENİ MAHALLE ATATÜRK BULVARI NO:29 ATAKUM',
        'phone'   => '0362 438 91 19',
        'email'   => 'moda.bisiklet@hotmail.com',
    ],
    [
        'city'    => 'TRABZON',
        'company' => 'İREM BİSİKLET',
        'address' => 'KARŞIYAKA MAH YAVUZ SELİM BULVARI NO:489 TANJANT YOLU',
        'phone'   => '0462 223 05 37',
        'email'   => 'info@irembisiklet.com',
    ],


];
